name: Checks

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.84.1"
      - name: Lint
        run: |
          rustup update
          rustup component add clippy
          cargo clippy
      - name: Audit
        run: |
          cargo install cargo-audit --locked
          cargo audit
      - name: Build
        run: |
          cargo build
      - name: Test
        run: |
          cargo test
