name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: rust
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.84.1"
      - name: Publish on crates.io
        env:
          CRATESIO_API_TOKEN: ${{ secrets.CRATESIO_API_TOKEN }}
        run: |
          cargo publish --token ${CRATESIO_API_TOKEN}
